import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { TransactionProvider } from "@/context/TransactionContext";
import { AuthProvider } from "@/context/AuthContext";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { useAuth } from "@/context/AuthContext";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <AuthProvider>
        <TransactionProvider>
        <SidebarProvider>
        <AppSidebar />
        <main className="flex flex-col flex-1">
           <Navbar/>
           {children}
           <ToastContainer position="bottom-right" autoClose={3000} />
        </main>
        </SidebarProvider>
        </TransactionProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
