import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { TransactionProvider } from "@/context/TransactionContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <TransactionProvider>
        <SidebarProvider>
        <AppSidebar />
        <main className="flex flex-col flex-1">
           <Navbar/>
           {children}
        </main>
        </SidebarProvider>
        </TransactionProvider>
      </body>
    </html>
  );
}
